name: Update Gist
on:
  release:
    types: [released]

jobs:
  update-gist:
    runs-on: ubuntu-20.04
    steps:
      - name: get latest.json download url
        id: get-download-url
        uses: actions/github-script@v6
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const update = latest.data.assets.find(a => a.name.includes("latest.json"))
            return update.browser_download_url
      - name: download latest.json
        run: wget ${{ steps.get-download-url.outputs.result }} -O ./updater.json
      - name: upload to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 3b82934f8560db6e988c49c22977c90f
          file_path: ./updater.json
          file_type: text
